name: Run dbt Model

on:
  workflow_dispatch: # This event triggers the workflow manually

jobs:
  run_dbt_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 # Set the desired Python version

      - name: Install dbt
        run: pip install dbt

      - name: Set environment variables
        env:
          DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
          DBT_SNOWFLAKE_USERNAME: ${{ secrets.DBT_SNOWFLAKE_USERNAME }}
          DBT_SNOWFLAKE_ROLE: ${{ secrets.DBT_SNOWFLAKE_ROLE }}
          DBT_SNOWFLAKE_PW: ${{ secrets.DBT_SNOWFLAKE_PW }}
          DBT_SNOWFLAKE_DATABASE: ${{ secrets.DBT_SNOWFLAKE_DATABASE }}
          DBT_SNOWFLAKE_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_WAREHOUSE }}
          DBT_SNOWFLAKE_SCHEMA: ${{ secrets.DBT_SNOWFLAKE_SCHEMA }}

      - name: Debug dbt Environment
        run: dbt debug --profile my_store

      - name: Run dbt Model
        run: dbt run -m your_model_name_here --profile my_store
