name: Run dbt Model

on:
  workflow_dispatch: # Allow manual triggering
  schedule:
    - cron: '0 23 * * *' # Run daily at 11 PM UTC

jobs:
  run_dbt_model:
    runs-on: ubuntu-latest

    env:
      DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT_PROD }}
      DBT_SNOWFLAKE_USERNAME: ${{ secrets.DBT_SNOWFLAKE_USERNAME_PROD }}
      DBT_SNOWFLAKE_ROLE: ${{ secrets.DBT_SNOWFLAKE_ROLE_PROD }}
      DBT_SNOWFLAKE_PW: ${{ secrets.DBT_SNOWFLAKE_PW_PROD }}
      DBT_SNOWFLAKE_DATABASE: ${{ secrets.DBT_SNOWFLAKE_DATABASE_PROD }}
      DBT_SNOWFLAKE_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_WAREHOUSE_PROD }}
      DBT_SNOWFLAKE_SCHEMA: ${{ secrets.DBT_SNOWFLAKE_SCHEMA_PROD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 # Set the desired Python version

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Debug dbt Environment
        run: dbt debug --profile my_store --target prod

      - name: Download dbt packages
        run: dbt deps 

      - name: Run dbt Model
        run: dbt run --target prod
