name: Run dbt Model

on:
  workflow_dispatch: # This event allows manual triggering

jobs:
  dbt_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify the Python version you need

    - name: Install dbt
      run: |
        pip install dbt
        dbt --version

    - name: Configure dbt
      run: |
        dbt debug # You can customize this step to configure your dbt project as needed

    - name: Run dbt model
      run: |
        dbt run # You can customize this step to run specific dbt models or tests

    # Optionally, you can add additional steps to notify or perform other actions after dbt completes.
